# Generated by Django 2.1.3 on 2019-01-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
